# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: $(Date:yyyy-MM-dd)-rev$(Rev:r)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: npm install
  displayName: npm install
- script: npx vue-cli-service lint --format junit 1> eslint.junit.b$BUILD_BUILID.xml
  displayName: npx vue-cli-service lint
- powershell: |
    $eslintFile = Join-Path . "eslint.junit.b$ENV:BUILD_BUILID.xml"
    if ([string]::IsNullOrWhiteSpace([System.IO.File]::ReadAllText($eslintFile))) {
      Remove-Item -Force -Verbose $eslintFile
    }
  displayName: Remove empty ESLint Result file (if any)
  continueOnError: true
- task: PublishTestResults@2
  displayName: 'Publish Lint Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: eslint.junit.*.xml
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testRunTitle: vue-cli-service lint
    buildPlatform: $(Agent.OS)-$(Agent.OSArchitecture)
  continueOnError: true
- script: npx vue-cli-service build --dest '$(Build.ArtifactStagingDirectory)'
  displayName: npm run build
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'dist' 
  continueOnError: true