# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
jobs:
- job: nodeJsLintBuild
  displayName: node.js Vue App CI
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: npm install
    displayName: npm install
  - task: PowerShell@2
    displayName: npx vue-cli-service lint
    inputs:
      targetType: filePath
      filePath: ci/ci-lint.ps1
      errorActionPreference: 'stop'
  - script: npx vue-cli-service build --dest '$(Build.ArtifactStagingDirectory)'
    displayName: npm run build
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'dist' 
    continueOnError: true